In [2]:
import numpy as np
import pandas as pd

In [3]:
#working numpy array
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print("\n Average number", arr.mean())


[10 20 30 40 50]

 Average number 30.0


In [4]:
#index
print(arr[3])
print(arr[-2])
print(arr[4])
print(arr[-4])

40
40
50
20


In [5]:
#slicing
print(arr[1:6])
print(arr[6:])
print(arr[:7])
print(arr[-6:-1])
print(arr[7:])
print(arr[-1:-6])



[20 30 40 50]
[]
[10 20 30 40 50]
[10 20 30 40]
[]
[]


In [6]:
#2Dimentional array
arr_2D = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr_2D[0,1])
print(arr_2D[1, : ])
print(arr_2D[1:2, 2])
print(arr_2D[2, :2])
print(arr_2D[1:3,0:2])


2
[4 5 6]
[6]
[7 8]
[[4 5]
 [7 8]]


In [7]:
#arrangement of array
arr_1 = np.arange(1,13)
reshape = arr_1.reshape(4,3)

print("original array:" , arr_1)
print("reshape array:\n", reshape)
flatten = reshape.flatten()
print("flatten to 1D:" , flatten)

original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
reshape array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
flatten to 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
#practice 
arr_20 = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(arr_20)
print(arr_20[-6:-2])
print(arr_20[-5:-1])
print(arr_20[-10:-5])



[ 2  4  6  8 10 12 14 16 18 20]
[10 12 14 16]
[12 14 16 18]
[ 2  4  6  8 10]


In [9]:
#practice2
arr_21 = np.arange(2,19,2)
print(arr_21)
reshape_21 = arr_21.reshape(3,3)
print(reshape_21)
print(reshape_21[0,0])
print(reshape_21[0,1])
print(reshape_21[0,2])
print(reshape_21[2,2])
print(reshape_21[0:1 , 0:3])


[ 2  4  6  8 10 12 14 16 18]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
2
4
6
18
[[2 4 6]]


In [10]:


#workin with basic mathematical operation

arr_2 = np.array([1, 2, 3, 4, 5])
arr_3 = np.array([10, 20, 30, 40, 50])

print(arr_2 + arr_3)
print(arr_2 - arr_3)
print(arr_2 * arr_3)
print(arr_3 / arr_2)

#scalar operation 
print(arr_3 **2)
print(arr_3//3)




[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[ 100  400  900 1600 2500]
[ 3  6 10 13 16]


In [11]:
#work with matrix using dot product
matrix_1 = np.array ([
    [1, 2],
    [2, 3]
])

matrix_2 = np.array([
    [5, 6],
    [7, 8]
])

dot = np.dot(matrix_1 , matrix_2)
print("matrix dot product\n" , dot)
print("matrix product\n" , matrix_1 * matrix_2 )


matrix dot product
 [[19 22]
 [31 36]]
matrix product
 [[ 5 12]
 [14 24]]


In [12]:
#work with daily steps analysis using numpy

np.random.seed(42) #reproducibility
days = np.arange(1,31)
steps = np.random.randint(3456, 12034 , size = 30)

data = pd.DataFrame({
    "days": days,
    "steps": steps
})

data

,days,steps
0,1,10726
1,2,4316
2,3,8846
3,4,8647
4,5,9190
5,6,9721
6,7,3922
7,8,7882
8,9,9034
9,10,11778


In [13]:
#basic stat

mean_steps = np.mean(steps)
std_steps = np.std(steps)
print("average steps:" , mean_steps)
print("standard deviation:" , std_steps)
print("median steps:", np.median(steps))
print("minimum steps:" , np.min(steps))
print("maximum steps:" , np.max(steps))


average steps: 7500.2
standard deviation: 2309.770715893679
median steps: 7946.5
minimum steps: 3645
maximum steps: 11778


In [21]:
#goal analysis steps exceed 10,000

goal = np.where(steps > 10000)[0] +1
print(goal)

[ 1 10 13 23]


In [23]:
#weekly analysis(split)
weeks = np.array_split(steps , 4)
print("weeks")
print(weeks)
print("week total")
week_total = [print(week.sum())for week in weeks]
print("\nweek average")
week_average = [print(week.mean())for week in weeks] 



weeks
[array([10726,  4316,  8846,  8647,  9190,  9721,  3922,  7882],
      dtype=int32), array([ 9034, 11778,  5141,  4225, 10405,  5889,  8767,  8507],
      dtype=int32), array([ 9876,  4640,  8011,  6841,  9852,  6014, 11305], dtype=int32), array([5503, 6203, 3645, 6190, 6461, 8114, 5355], dtype=int32)]
week total
63250
63746
56539
41471

week average
7906.25
7968.25
8077.0
5924.428571428572


In [25]:
window = 7
moving_average = np.convolve(steps, np.ones(window)/window, mode = "valid")
print("rolling movint average", moving_average[:7])

rolling movint average [7909.71428571 7503.42857143 8177.42857143 8596.28571429 8095.42857143
 7386.14285714 7483.85714286]


In [28]:
#anomaly detection

lower_bound = mean_steps - 2*std_steps
upper_bound = mean_steps + 2*std_steps

print(lower_bound)
print(upper_bound)

anomaly = np.where((steps < lower_bound) | (steps > upper_bound))[0] + 1

print("anomaly detection low/high:" , anomaly)

2880.6585682126415
12119.741431787359
anomaly detection low/high: []
